### ISSUE TITLE
Zul updating from 8.5.0 to 9.0.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [zkoss/zk#1840]
When I try to upgrade zul from 8.5.0 to version after 8.6.0.1. The following code breaks.
```
public class Testzul {
	
    @Test
    public void testRemoveAllChildren()
    {
        Listbox listbox = new Listbox();
        Assert.assertEquals(0, listbox.getChildren().size());

        Listitem listitem = new Listitem();
        listbox.appendChild(listitem);
        Assert.assertEquals(1, listbox.getChildren().size());

        ComponentHelper.removeAllChildren(listbox);
        Assert.assertEquals(0, listbox.getChildren().size());
    }

}
```
```
public class ComponentHelper
{
    public static void removeAllChildren(Component component)
    {
        List<Component> removableComponents = new ArrayList<Component>();

        for (Component children : component.getChildren())
        {
            removableComponents.add(children);
        }

        for (Component removableComponent : removableComponents)
        {
            component.removeChild(removableComponent);
        }
    }
}
```

The code should pass, but it throws an error:
```
java.lang.NullPointerException
	at org.zkoss.zk.ui.AbstractComponent.beforeParentChanged(AbstractComponent.java:1986)
	at org.zkoss.zul.Listitem.beforeParentChanged(Listitem.java:395)
	at org.zkoss.zk.ui.AbstractComponent.setParent(AbstractComponent.java:1211)
	at org.zkoss.zk.ui.AbstractComponent.removeChild(AbstractComponent.java:1562)
	at org.zkoss.zul.Listbox.removeChild(Listbox.java:1858)
	at ComponentHelper.removeAllChildren(ComponentHelper.java:21)
	at Testzul.testRemoveAllChildren(Testzul.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)


```

**Comment by scribetw** [comment]
Since there is no any `WebApp` instance available, an NPE was thrown.
Without a `WebApp`, most functionality is unavailable.

Try mocking a `WebApp` before your test case:
```java
@BeforeClass
public static void beforeClass() throws Exception {
	SimpleWebApp wapp = new SimpleWebApp();
	wapp.init(PowerMockito.mock(ServletContext.class), new Configuration());
	WebAppsCtrl.setCurrent(wapp);
}
```

**Comment by SElab2019** [comment]
Hi @scribetw , thanks for your help. It solved my issue. Btw would it be better to add a breaking announcement in the release note? Then all other developers who use zul can know it.
